http:
  routers:
    pushav-router:
      rule: "PathPrefix(`/pushav`)"
      service: pushav-service
      middlewares:
        - pushav-stripprefix
  services:
    pushav-service:
      loadBalancer:
        servers:
          - url: "https://host.docker.internal:1234"
        serversTransport: insecure-transport
  middlewares:
    pushav-stripprefix:
      stripPrefix:
        prefixes:
          - "/pushav"
  serversTransports:
    insecure-transport:
      insecureSkipVerify: true
