name: Build Docker Images

on:
  workflow_dispatch:
    inputs:
      target_branch_or_tag:
        required: true
  push:
    tags:
      - v*

jobs:
  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository when push
        if: github.event_name == 'push'
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Checkout repository when input
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.target_branch_or_tag }}
          submodules: recursive
          fetch-depth: 0

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get submodules commit IDs
        id: submodules
        run: |
          echo "backend_sha=$(cd backend && git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT
          echo "frontend_sha=$(cd frontend && git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

      - name: Extract metadata for backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/csa-certification-tool-backend
          tags: |
            type=raw,value=${{ steps.submodules.outputs.backend_sha }}

      - name: Extract metadata for frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/csa-certification-tool-frontend
          tags: |
            type=raw,value=${{ steps.submodules.outputs.frontend_sha }}
      
      - name: Print tags
        run: |
            echo "${{ steps.meta-backend.outputs.tags }}"
            echo "${{ steps.meta-frontend.outputs.tags }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64, linux/arm64
      
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
